 <footer>
        CSC 174: Advanced Front-end Web Design and Development
    </footer>
<nav>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="freshman-spring.php">Freshman Spring</a></li>
            <li><a href="sophomore.php">Sophomore Year</a></li>
            <li><a href="final-years.php">Junior and Senior Year</a></li>
        </ul>
    </nav>
<script src="https://code.jquery.com/jquery.js"></script>
    <script src="js/menu-highlighter.js"></script>
    </body>