<head>
    <meta charset="utf-8" />
    <title>Luke Oluoch | Lab 01</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/styles.css" />
</head>
<body class ="container">
    <header>
    <a href="index.html">
        <h1>Luke Oluoch</h1>
        <img src="images/luke.jpg" alt="Image Of Luke Oluoch">
    </a>
    
    </header>
    <aside>
        <ul>
            <li>Name: Luke Oluoch</li>
            <li>Major: Chemical Engineering</li>
            <li>Class Year: 2019</li>
        </ul>
        <div>A yearly retrospective about my academic experience at the University of Rochester.</div>
    </aside>